# 1.0-exploratory-data-analysis

In [2]:
import pandas as pd

In [3]:
sc_player_data = pd.read_csv('../data/external/starcraft_player_data.csv')

## First Look at the Data

In [5]:
sc_player_data.head()

,GameID,LeagueIndex,Age,HoursPerWeek,TotalHours,APM,SelectByHotkeys,AssignToHotkeys,UniqueHotkeys,MinimapAttacks,MinimapRightClicks,NumberOfPACs,GapBetweenPACs,ActionLatency,ActionsInPAC,TotalMapExplored,WorkersMade,UniqueUnitsMade,ComplexUnitsMade,ComplexAbilitiesUsed
0,52,5,27,10,3000,143.7180,0.003515,0.000220,7,0.000110,0.000392,0.004849,32.6677,40.8673,4.7508,28,0.001397,6,0.0,0.000000
1,55,5,23,10,5000,129.2322,0.003304,0.000259,4,0.000294,0.000432,0.004307,32.9194,42.3454,4.8434,22,0.001193,5,0.0,0.000208
2,56,4,30,10,200,69.9612,0.001101,0.000336,4,0.000294,0.000461,0.002926,44.6475,75.3548,4.0430,22,0.000745,6,0.0,0.000189
3,57,3,19,20,400,107.6016,0.001034,0.000213,1,0.000053,0.000543,0.003783,29.2203,53.7352,4.9155,19,0.000426,7,0.0,0.000384
4,58,3,32,10,500,122.8908,0.001136,0.000327,2,0.000000,0.001329,0.002368,22.6885,62.0813,9.3740,15,0.001174,4,0.0,0.000019

In [39]:
sc_player_data.describe()

,GameID,LeagueIndex,APM,SelectByHotkeys,AssignToHotkeys,UniqueHotkeys,MinimapAttacks,MinimapRightClicks,NumberOfPACs,GapBetweenPACs,ActionLatency,ActionsInPAC,TotalMapExplored,WorkersMade,UniqueUnitsMade,ComplexUnitsMade,ComplexAbilitiesUsed
count,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000,3395.000000
mean,4805.012371,4.184094,117.046947,0.004299,0.000374,4.364654,0.000098,0.000387,0.003463,40.361562,63.739403,5.272988,22.131664,0.001032,6.534021,0.000059,0.000142
std,2719.944851,1.517327,51.945291,0.005284,0.000225,2.360333,0.000166,0.000377,0.000992,17.153570,19.238869,1.494835,7.431719,0.000519,1.857697,0.000111,0.000265
min,52.000000,1.000000,22.059600,0.000000,0.000000,0.000000,0.000000,0.000000,0.000679,6.666700,24.093600,2.038900,5.000000,0.000077,2.000000,0.000000,0.000000
25%,2464.500000,3.000000,79.900200,0.001258,0.000204,3.000000,0.000000,0.000140,0.002754,28.957750,50.446600,4.272850,17.000000,0.000683,5.000000,0.000000,0.000000
50%,4874.000000,4.000000,108.010200,0.002500,0.000353,4.000000,0.000040,0.000281,0.003395,36.723500,60.931800,5.095500,22.000000,0.000905,6.000000,0.000000,0.000020
75%,7108.500000,5.000000,142.790400,0.005133,0.000499,6.000000,0.000119,0.000514,0.004027,48.290500,73.681300,6.033600,27.000000,0.001259,8.000000,0.000086,0.000181
max,10095.000000,8.000000,389.831400,0.043088,0.001752,10.000000,0.003019,0.004041,0.007971,237.142900,176.372100,18.558100,58.000000,0.005149,13.000000,0.000902,0.003084

In [40]:
sc_player_data.dtypes

GameID                    int64
LeagueIndex               int64
Age                      object
HoursPerWeek             object
TotalHours               object
APM                     float64
SelectByHotkeys         float64
AssignToHotkeys         float64
UniqueHotkeys             int64
MinimapAttacks          float64
MinimapRightClicks      float64
NumberOfPACs            float64
GapBetweenPACs          float64
ActionLatency           float64
ActionsInPAC            float64
TotalMapExplored          int64
WorkersMade             float64
UniqueUnitsMade           int64
ComplexUnitsMade        float64
ComplexAbilitiesUsed    float64
dtype: object

## Datatype Inconsistencies!
The provided data dictionary states that features Age, HoursPerWeek, and TotalHours should be integer datatypes. However, Pandas decided to designate these features as objects. This would indicate that there the values in the column are either str or mixed with numeric and non-numeric values.

Let's check the values in each of these columns.

In [34]:
sc_player_data['Age'].unique()

array(['27', '23', '30', '19', '32', '21', '17', '20', '18', '16', '26',
       '38', '28', '25', '22', '29', '24', '35', '31', '33', '37', '40',
       '34', '43', '41', '36', '44', '39', '?'], dtype=object)

In [35]:
sc_player_data['HoursPerWeek'].unique()

array(['10', '20', '6', '8', '42', '14', '24', '16', '4', '12', '30',
       '28', '70', '2', '56', '36', '40', '18', '96', '50', '168', '48',
       '84', '0', '72', '112', '90', '32', '98', '140', '?', '80', '60'],
      dtype=object)

In [43]:
sc_player_data['TotalHours'].unique()

array(['3000', '5000', '200', '400', '500', '70', '240', '10000', '2708',
       '800', '6000', '190', '350', '1000', '1500', '2000', '120', '1100',
       '2520', '700', '160', '150', '250', '730', '230', '300', '100',
       '270', '1200', '30', '600', '540', '280', '1600', '50', '140',
       '900', '550', '625', '1300', '450', '750', '612', '180', '770',
       '720', '415', '1800', '2200', '480', '430', '639', '360', '1250',
       '365', '650', '233', '416', '1825', '780', '1260', '315', '10',
       '312', '110', '1700', '92', '2500', '1400', '220', '999', '303',
       '96', '184', '4000', '420', '60', '2400', '2160', '80', '25',
       '624', '176', '?', '35', '1163', '333', '75', '7', '40', '325',
       '90', '175', '88', '850', '26', '1650', '465', '235', '1350',
       '460', '848', '256', '130', '1466', '670', '711', '1030', '1080',
       '1460', '1050', '20000', '582', '2800', '553', '1008', '330',
       '936', '243', '1320', '425', '1145', '366', '2700', '830', '3',
       '125', '2300', '336', '24', '12', '72', '690', '320', '144', '20',
       '1155', '520', '865', '275', '548', '170', '898', '1170', '1148',
       '105', '575', '1850', '238', '820', '310', '85', '2942', '94',
       '2100', '224', '165', '577', '1440', '731', '727', '138', '45',
       '225', '95', '630', '1274', '1782', '610', '525', '2671', '2016',
       '123', '1095', '1000000', '2920', '640', '1344', '1940', '16',
       '410', '960', '740', '950', '551', '216', '840', '18000', '745',
       '530', '477', '1270', '36', '174', '2600', '1256', '9000', '1880',
       '288', '1150', '10260', '2190', '560', '25000', '128', '666',
       '854', '370', '65', '334', '755', '1024', '3257', '208', '1196',
       '1870', '990', '470', '699', '340', '2250', '255', '980', '620',
       '380', '196', '21', '153', '1098', '546', '433', '1560', '580',
       '77', '148', '2880', '364', '56'], dtype=object)

As expected, there are str values in these columns '?', which represent missing values.

Let's now explore the rows with these '?' values.

In [53]:
temp = sc_player_data[['LeagueIndex','Age','HoursPerWeek','TotalHours']]

In [57]:
# How many rows have '?' in the Age column?
temp[temp['Age']=='?']

      LeagueIndex Age HoursPerWeek TotalHours
3340            8   ?            ?          ?
3341            8   ?            ?          ?
3342            8   ?            ?          ?
3343            8   ?            ?          ?
3344            8   ?            ?          ?
3345            8   ?            ?          ?
3346            8   ?            ?          ?
3347            8   ?            ?          ?
3348            8   ?            ?          ?
3349            8   ?            ?          ?
3350            8   ?            ?          ?
3351            8   ?            ?          ?
3352            8   ?            ?          ?
3353            8   ?            ?          ?
3354            8   ?            ?          ?
3355            8   ?            ?          ?
3356            8   ?            ?          ?
3357            8   ?            ?          ?
3358            8   ?            ?          ?
3359            8   ?            ?          ?
3360            8   ?            ?          ?
3361            8   ?            ?          ?
3362            8   ?            ?          ?
3363            8   ?            ?          ?
3364            8   ?            ?          ?
3365            8   ?            ?          ?
3366            8   ?            ?          ?
3367            8   ?            ?          ?
3368            8   ?            ?          ?
3369            8   ?            ?          ?
3370            8   ?            ?          ?
3371            8   ?            ?          ?
3372            8   ?            ?          ?
3373            8   ?            ?          ?
3374            8   ?            ?          ?
3375            8   ?            ?          ?
3376            8   ?            ?          ?
3377            8   ?            ?          ?
3378            8   ?            ?          ?
3379            8   ?            ?          ?
3380            8   ?            ?          ?
3381            8   ?            ?          ?
3382            8   ?            ?          ?
3383            8   ?            ?          ?
3384            8   ?            ?          ?
3385            8   ?            ?          ?
3386            8   ?            ?          ?
3387            8   ?            ?          ?
3388            8   ?            ?          ?
3389            8   ?            ?          ?
3390            8   ?            ?          ?
3391            8   ?            ?          ?
3392            8   ?            ?          ?
3393            8   ?            ?          ?
3394            8   ?            ?          ?

In [58]:
# How many rows have '?' in the HoursPerWeek column?
temp[temp['HoursPerWeek']=='?']

      LeagueIndex Age HoursPerWeek TotalHours
1841            5  18            ?          ?
3340            8   ?            ?          ?
3341            8   ?            ?          ?
3342            8   ?            ?          ?
3343            8   ?            ?          ?
3344            8   ?            ?          ?
3345            8   ?            ?          ?
3346            8   ?            ?          ?
3347            8   ?            ?          ?
3348            8   ?            ?          ?
3349            8   ?            ?          ?
3350            8   ?            ?          ?
3351            8   ?            ?          ?
3352            8   ?            ?          ?
3353            8   ?            ?          ?
3354            8   ?            ?          ?
3355            8   ?            ?          ?
3356            8   ?            ?          ?
3357            8   ?            ?          ?
3358            8   ?            ?          ?
3359            8   ?            ?          ?
3360            8   ?            ?          ?
3361            8   ?            ?          ?
3362            8   ?            ?          ?
3363            8   ?            ?          ?
3364            8   ?            ?          ?
3365            8   ?            ?          ?
3366            8   ?            ?          ?
3367            8   ?            ?          ?
3368            8   ?            ?          ?
3369            8   ?            ?          ?
3370            8   ?            ?          ?
3371            8   ?            ?          ?
3372            8   ?            ?          ?
3373            8   ?            ?          ?
3374            8   ?            ?          ?
3375            8   ?            ?          ?
3376            8   ?            ?          ?
3377            8   ?            ?          ?
3378            8   ?            ?          ?
3379            8   ?            ?          ?
3380            8   ?            ?          ?
3381            8   ?            ?          ?
3382            8   ?            ?          ?
3383            8   ?            ?          ?
3384            8   ?            ?          ?
3385            8   ?            ?          ?
3386            8   ?            ?          ?
3387            8   ?            ?          ?
3388            8   ?            ?          ?
3389            8   ?            ?          ?
3390            8   ?            ?          ?
3391            8   ?            ?          ?
3392            8   ?            ?          ?
3393            8   ?            ?          ?
3394            8   ?            ?          ?

In [60]:
# How many rows have '?' in the TotalHours column?
temp[temp['TotalHours']=='?']

    index  LeagueIndex Age HoursPerWeek TotalHours
0     358            5  17           20          ?
1    1841            5  18            ?          ?
2    3340            8   ?            ?          ?
3    3341            8   ?            ?          ?
4    3342            8   ?            ?          ?
5    3343            8   ?            ?          ?
6    3344            8   ?            ?          ?
7    3345            8   ?            ?          ?
8    3346            8   ?            ?          ?
9    3347            8   ?            ?          ?
10   3348            8   ?            ?          ?
11   3349            8   ?            ?          ?
12   3350            8   ?            ?          ?
13   3351            8   ?            ?          ?
14   3352            8   ?            ?          ?
15   3353            8   ?            ?          ?
16   3354            8   ?            ?          ?
17   3355            8   ?            ?          ?
18   3356            8   ?            ?          ?
19   3357            8   ?            ?          ?
20   3358            8   ?            ?          ?
21   3359            8   ?            ?          ?
22   3360            8   ?            ?          ?
23   3361            8   ?            ?          ?
24   3362            8   ?            ?          ?
25   3363            8   ?            ?          ?
26   3364            8   ?            ?          ?
27   3365            8   ?            ?          ?
28   3366            8   ?            ?          ?
29   3367            8   ?            ?          ?
30   3368            8   ?            ?          ?
31   3369            8   ?            ?          ?
32   3370            8   ?            ?          ?
33   3371            8   ?            ?          ?
34   3372            8   ?            ?          ?
35   3373            8   ?            ?          ?
36   3374            8   ?            ?          ?
37   3375            8   ?            ?          ?
38   3376            8   ?            ?          ?
39   3377            8   ?            ?          ?
40   3378            8   ?            ?          ?
41   3379            8   ?            ?          ?
42   3380            8   ?            ?          ?
43   3381            8   ?            ?          ?
44   3382            8   ?            ?          ?
45   3383            8   ?            ?          ?
46   3384            8   ?            ?          ?
47   3385            8   ?            ?          ?
48   3386            8   ?            ?          ?
49   3387            8   ?            ?          ?
50   3388            8   ?            ?          ?
51   3389            8   ?            ?          ?
52   3390            8   ?            ?          ?
53   3391            8   ?            ?          ?
54   3392            8   ?            ?          ?
55   3393            8   ?            ?          ?
56   3394            8   ?            ?          ?

As the features HoursPerWeek and TotalHours have rows that contain '?' but inputed values in the other columns, it is important to be careful to note these edge cases and not assume that a '?' value automatically indicates that the other features will have a '?' as well.

In [23]:
sc_player_data.astype({'Age': 'int32','HoursPerWeek':'int32','TotalHours':'int32'})

ValueError: invalid literal for int() with base 10: '?': Error while type casting for column 'Age'

In [21]:
# Checking if there are any missing values 
sc_player_data.isna().sum()

GameID                  0
LeagueIndex             0
Age                     0
HoursPerWeek            0
TotalHours              0
APM                     0
SelectByHotkeys         0
AssignToHotkeys         0
UniqueHotkeys           0
MinimapAttacks          0
MinimapRightClicks      0
NumberOfPACs            0
GapBetweenPACs          0
ActionLatency           0
ActionsInPAC            0
TotalMapExplored        0
WorkersMade             0
UniqueUnitsMade         0
ComplexUnitsMade        0
ComplexAbilitiesUsed    0
dtype: int64

In [15]:
# For each potential feature, group by LeagueIndex and aggregate
def aggregate_by_index(feature: str):
    sc_player_data.groupby(by=['LeagueIndex'])[feature].mean()
    return aggregates

In [16]:
aggregate_by_index('HoursPerWeek')

TypeError: Could not convert 10103016101410201062016812285624126810620620141028183681212241412101012208101210101014102048881224281014108281282889616422820123082816201428424620128201640242024816428246164224424146186428242812148812242010161628121081014108620201020101410824212306281424242061816102102410126810201410201086363016212201028886102088208241624416162828162428642842281014122810828646421412362028102062042201628616141656562028642141286121020201410102882861448282428882082414146106202010820121216688816204102812168362812704228424101624420101012101042482416102010101228561612209012248421212122462041420161041020282012203614122042014162070103016422820201442010282416281224142062022882410161412421020628281236106201082610244108148282824202105664204282424242816882828841464?286101016242048203061212101241024101228668410201666210106481010281666420414166106423028122012281014281016816162881628616214106624121061266144101022010101610410230122020122414142066108242441210428161616421686281682021014612241046620122424162020282828241020810281642644242428122010122010420884228122084218610624212202436284885684828141062842121016242422830104221010163688442101241028162812410421810242442610228242416143618286202410201028288308282012882812106108444168108122020610428420610201256428421264242488123616824144282828824824612202416122428101420402882412204210202030828201214666662881016604168162041641210101616624128414420456 to numeric

In [11]:
sc_player_data.groupby(by=['LeagueIndex'])['GapBetweenPACs'].mean()

LeagueIndex
1    65.654987
2    53.788886
3    46.143882
4    41.041426
5    34.726473
6    30.207895
7    22.978160
8    18.969773
Name: GapBetweenPACs, dtype: float64